# This is an example Database configuration file. 

# You will need to create a database.yml file within the 
# config/ directory to run this application. 

# You can copy the contents of this file to get you started.
#
# This specifies the database type as PostGres, which is recommended, as this
# is what Open Plaques uses in production.
#
# Postgres can be installed in a variety of ways. For OSX, the easiest is to install
# this app: http://postgresapp.com
#
# Alternatively, you can try using a different database type, such as SQLite3.
# These *should* mostly work, but you may experience some errors where the database
# differs from PostGres.
#
development:
  adapter: postgresql
  database: openplaques
  encoding: unicode  

test:
  adapter: postgresql
  database: openplaques_test
  encoding: unicode